- name: Installs zsh
  become: yes
  become_user: root
  apt:
    name: 
    - zsh
    state: present

- name: Installs curl 
  become: yes
  become_user: root
  apt:
    name: 
    - curl
    state: present

- name: set up zsh for user
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ lookup('env', 'USER') }}

- name: Checks for zinit installation 
  stat:
    path: "{{ lookup('env', 'HOME') }}/.zinit"
  register: zinit_stat

- name: Installs zinit 
  raw: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"' 
  when: not zinit_stat.stat.exists

- name: Copy my .zshrc
  command: curl -LSso ~/.zshrc https://raw.github.com/fhumayun/dotfiles/master/.zshrc 
  sudo: no
